name: main-pipeline

on:
    push:
        branches: [main]

jobs:
    build_test_workflow:
        uses: ./.github/workflows/reusable-build-test.yml
        with:
            python-version: '3.12'
            run_tests: true
            
    generate-sha:
        needs: build_test_workflow
        runs-on: ubuntu-latest
        outputs:
            short_sha: ${{ steps.sha_id.outputs.short_sha }}
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: Get the short sha
              id: sha_id
              run: |
                echo "short_sha=$(git rev-parse HEAD | cut -c 1-7)" >> $GITHUB_OUTPUT

    reusable-docker-backend-workflow:
        needs: [build_test_workflow, generate-sha]
        uses: ./.github/workflows/reusable-docker-backend.yml
        with:
            image: coding-mentor-ai-backend
            tags: "sha-${{ needs.generate-sha.outputs.short_sha }}"
        secrets: 
             docker_username: ${{ secrets.DOCKER_USERNAME }}
             docker_token: ${{ secrets.DOCKER_PASSWORD }}

    reusable-docker-frontend-workflow:
        needs: [build_test_workflow, generate-sha]
        uses: ./.github/workflows/reusable-docker-frontend.yml
        with:
            image: coding-mentor-ai-frontend
            tags: "sha-${{ needs.generate-sha.outputs.short_sha }}"
        secrets: 
            docker_username: ${{ secrets.DOCKER_USERNAME }}
            docker_token: ${{ secrets.DOCKER_PASSWORD }}

    security-element:
        needs: [reusable-docker-frontend-workflow, reusable-docker-backend-workflow]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Scan the code for backend image
              uses: aquasecurity/trivy-action@master
              env: 
                  TRIVY_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
                  TRIVY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              with:
                  image-ref: ${{ secrets.DOCKER_USERNAME }}/coding-mentor-ai-backend:latest
                  exit-code: '1'
                  format: 'table'
                  severity: 'CRITICAL,HIGH'
                  trivyignores: '.trivyignore'

            - name: Scan the code for Frontend image
              uses: aquasecurity/trivy-action@master
              env: 
                  TRIVY_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
                  TRIVY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              with:
                  image-ref: ${{ secrets.DOCKER_USERNAME }}/coding-mentor-ai-frontend:latest
                  exit-code: '1'
                  format: 'table'
                  severity: 'CRITICAL,HIGH'
                  trivyignores: '.trivyignore'



    deploy:
        runs-on: ubuntu-latest
        environment: production
        needs: [reusable-docker-backend-workflow, reusable-docker-frontend-workflow, security-element]
        steps:
            - name: Print the default message
              run: |
                  echo "Backend Image published: <${{ needs.reusable-docker-backend-workflow.outputs.my_output }}>"
                  echo "Frontend Image published: <${{ needs.reusable-docker-frontend-workflow.outputs.my_output }}>"
                  echo "Deploying both microservices to production environment gates."
